"""
RightWrite - 多年級生字資料
支援：四下-康軒版、二下-翰林版
同音字(homophones)用於生成錯字練習
"""

# 年級資料註冊表
GRADE_REGISTRY = {
    "grade4": {
        "label": "四下-康軒版",
        "semester": "114學年度第2學期",
        "grade": "四年級",
        "publisher": "康軒版",
        "total_lessons": 12,
        "midterm_range": (1, 6),
        "final_range": (7, 12),
    },
    "grade2": {
        "label": "二下-翰林版",
        "semester": "114學年度第2學期",
        "grade": "二年級",
        "publisher": "翰林版",
        "total_lessons": 12,
        "midterm_range": (1, 6),
        "final_range": (7, 12),
    },
}

# ---------- 四下-康軒版 ----------

VOCAB_DATA_GRADE4 = {
    1: {
        "title": "一束鮮花",
        "characters": [
            {"char": "潔", "similar_wrong": ["節", "結", "截", "傑"], "examples": []},
            {"char": "環", "similar_wrong": ["幻", "患", "喚"], "examples": ["充足的睡眠，是保持健康的重要一環。"]},
            {"char": "境", "similar_wrong": ["敬", "靜", "竟"], "examples": []},
            {"char": "甚", "similar_wrong": ["慎"], "examples": ["你這種態度簡直是欺人太甚了！", "我不但不了解這件事，甚至聽都沒聽過。"]},
            {"char": "至", "similar_wrong": ["治", "製", "秩", "智", "致"], "examples": []},
            {"char": "懶", "similar_wrong": ["籃", "欄", "藍"], "examples": []},
            {"char": "梳", "similar_wrong": ["舒", "疏", "殊", "蔬", "輸"], "examples": []},
            {"char": "髒", "similar_wrong": ["葬", "藏", "臟"], "examples": ["他的房間又髒又亂。", "快到餐廳去吃，別髒了我的房間。"]},
            {"char": "臭", "similar_wrong": ["仇", "愁", "醜"], "examples": []},
            {"char": "雜", "similar_wrong": ["砸", "扎"], "examples": ["圖書室內有多種雜誌，可供讀者借閱"]},
            {"char": "調", "similar_wrong": ["掉"], "examples": ["調皮的孩子通常都很聰明。"]},
            {"char": "叢", "similar_wrong": ["從"], "examples": []},
            {"char": "暢", "similar_wrong": ["唱"], "examples": []},
            {"char": "格", "similar_wrong": ["閣", "隔", "革"], "examples": ["感冒藥水每次喝一格，三餐飯後服用。", "那本書放在書架的第三格。"]},
            {"char": "言", "similar_wrong": ["炎", "嚴", "顏", "研"], "examples": []},
        ],
        "compounds": [
            {"word": "潔白", "examples": ["她穿了一身潔白的衣服，看起來像天女下凡。"]},
            {"word": "環境", "examples": ["社會環境、學習環境、居住環境"]},
            {"word": "甚至", "examples": ["他忙得甚至連吃飯時間都沒有。"]},
            {"word": "懶散", "examples": ["為了避免退休後日漸懶散，他決定投身社會的公益活動。"]},
            {"word": "雜亂", "examples": ["他日夜繁忙，疏於打理家務，屋內雜亂不堪。"]},
            {"word": "調和", "examples": ["廚師善於調和五味，烹飪佳餚。", "他們倆人爭執不休，你還是居中調和調和吧！"]},
            {"word": "雜草叢生", "examples": ["後院荒廢已久，處處雜草叢生。"]},
            {"word": "舒暢", "examples": []},
            {"word": "格格不入", "examples": ["這幅西洋油畫掛在古色古香的大廳上，顯得格格不入。"]},
            {"word": "自言自語", "examples": ["只見他高興得手舞足蹈，自言自語，不知有什麼奇思妙想？"]},
        ],
    },
    2: {
        "title": "心動不如行動",
        "characters": [
            {"char": "川", "similar_wrong": ["穿"], "examples": []},
            {"char": "缺", "similar_wrong": ["確"], "examples": []},
            {"char": "窮", "similar_wrong": ["瓊"], "examples": []},
            {"char": "繼", "similar_wrong": ["寂", "忌", "記", "技", "既"], "examples": []},
            {"char": "研", "similar_wrong": ["言", "炎", "嚴", "顏"], "examples": []},
            {"char": "既", "similar_wrong": ["紀", "寂", "技", "季", "記"], "examples": []},
            {"char": "租", "similar_wrong": ["阻", "族", "祖"], "examples": []},
            {"char": "備", "similar_wrong": ["背", "貝", "倍", "被"], "examples": []},
            {"char": "缽", "similar_wrong": ["剝", "撥", "播", "波"], "examples": []},
            {"char": "緣", "similar_wrong": ["源", "原", "圓", "元", "園"], "examples": ["那位師父沿街化緣。"]},
            {"char": "達", "similar_wrong": ["答"], "examples": []},
            {"char": "慚", "similar_wrong": ["慘"], "examples": []},
            {"char": "愧", "similar_wrong": ["窺"], "examples": []},
            {"char": "慮", "similar_wrong": ["率", "律", "綠"], "examples": []},
            {"char": "絆", "similar_wrong": ["拌", "辦", "伴", "半"], "examples": []},
        ],
        "compounds": [
            {"word": "窮困", "examples": ["雖然家境清寒，生活窮困，他仍然勤奮向學。"]},
            {"word": "三餐不繼", "examples": ["他因生意失敗，導致全家三餐不繼。"]},
            {"word": "研讀", "examples": ["老師指導我們研讀課外書刊，以增廣知識。"]},
            {"word": "準備", "examples": ["事前有充分的準備，臨時才不會手忙腳亂。", "明天的宴會我不準備參加了。"]},
            {"word": "化緣", "examples": ["為籌措修繕古剎的經費，住持和尚到處化緣。"]},
            {"word": "到達", "examples": ["依目前的情形估計，我們大約下午三點鐘可到達目的地。"]},
            {"word": "慚愧", "examples": ["他在發現自己做錯事後，感到十分慚愧後悔。", "本人不才，竟能獲獎，真是慚愧！慚愧！"]},
            {"word": "顧慮", "examples": ["確立奮鬥目標後，即當放手去做，不必顧慮太多！"]},
            {"word": "絆腳石", "examples": ["猶豫是成功的絆腳石。"]},
        ],
    },
    3: {
        "title": "選拔動物之星",
        "characters": [
            {"char": "啟", "similar_wrong": ["企"], "examples": []},
            {"char": "宣", "similar_wrong": ["玄", "旋", "選"], "examples": []},
            {"char": "選", "similar_wrong": ["宣", "玄", "旋"], "examples": []},
            {"char": "勤", "similar_wrong": ["琴"], "examples": []},
            {"char": "健", "similar_wrong": ["見", "劍", "賤", "漸", "件"], "examples": ["老來多健忘"]},
            {"char": "厲", "similar_wrong": ["力", "粒", "立", "利", "歷"], "examples": []},
            {"char": "蝸", "similar_wrong": ["窩"], "examples": ["蝸牛走過的地方，會留下一道白色透明的黏液。"]},
            {"char": "寸", "similar_wrong": ["村", "存"], "examples": []},
            {"char": "駱", "similar_wrong": ["絡", "落"], "examples": []},
            {"char": "駝", "similar_wrong": ["脫", "拖", "託"], "examples": []},
            {"char": "皺", "similar_wrong": ["宙", "咒"], "examples": []},
            {"char": "眉", "similar_wrong": ["沒", "媒", "玫", "梅"], "examples": ["幾經調查，案情終於有點眉目了。", "近在眉目之間"]},
            {"char": "艘", "similar_wrong": ["搜", "嫂"], "examples": []},
            {"char": "艇", "similar_wrong": ["挺"], "examples": []},
            {"char": "拭", "similar_wrong": ["事", "似", "式", "視", "示"], "examples": []},
        ],
        "compounds": [
            {"word": "啟事", "examples": ["尋人啟事、道歉啟事、遺失啟事"]},
            {"word": "宣傳", "examples": ["這部影片的主角近日將隨片來臺，進行宣傳。", "他是這位名歌手的宣傳，幹練又有衝勁。"]},
            {"word": "選拔", "examples": ["他在這次歌唱選拔大賽中表現優異，從眾多參賽者中脫穎而出。"]},
            {"word": "勤奮", "examples": ["他工作勤奮，正一步步朝自己的理想前進。"]},
            {"word": "剛健", "examples": ["剛健中正、剛健篤實"]},
            {"word": "厲害", "examples": ["他看了那幕驚險的鏡頭，心跳得很厲害。", "他的劍法非常厲害，一般人根本不是他的對手。"]},
            {"word": "蝸牛", "examples": ["蝸牛走過的地方，會留下一道白色透明的黏液。"]},
            {"word": "駱駝", "examples": ["駱駝的胃裡有可儲水的小泡泡，所以牠可以好幾天不喝水。"]},
            {"word": "眉頭", "examples": ["他心情不佳，終日眉頭深鎖。"]},
            {"word": "遊艇", "examples": ["每逢假日，他喜歡和幾個朋友乘遊艇到外海垂釣。"]},
            {"word": "拭目以待", "examples": ["他撰寫的新書即將出版，許多讀者都拭目以待。"]},
        ],
    },
    4: {
        "title": "米食飄香",
        "characters": [
            {"char": "稻", "similar_wrong": ["盜", "倒", "道", "到"], "examples": []},
            {"char": "米", "similar_wrong": ["秘", "祕", "密"], "examples": []},
            {"char": "粒", "similar_wrong": ["力", "立", "利", "歷", "厲"], "examples": []},
            {"char": "蘿", "similar_wrong": ["裸", "絡", "囉"], "examples": []},
            {"char": "蔔", "similar_wrong": ["伯"], "examples": []},
            {"char": "漿", "similar_wrong": ["將", "江"], "examples": []},
            {"char": "蒸", "similar_wrong": ["掙", "征", "箏", "爭"], "examples": []},
            {"char": "鹹", "similar_wrong": ["賢", "閒", "嫌", "弦"], "examples": []},
            {"char": "財", "similar_wrong": ["才", "材"], "examples": []},
            {"char": "粿", "similar_wrong": ["果"], "examples": []},
            {"char": "艾", "similar_wrong": ["愛"], "examples": ["問題既然發生了，就應該力謀解決之道，一味自怨自艾是無濟於事的。"]},
            {"char": "康", "similar_wrong": ["抗"], "examples": []},
            {"char": "粽", "similar_wrong": ["宗", "總"], "examples": ["這家店賣的粽子很好吃。"]},
            {"char": "推", "similar_wrong": ["退"], "examples": []},
            {"char": "陳", "similar_wrong": ["沉", "臣", "晨"], "examples": []},
        ],
        "compounds": [
            {"word": "稻米", "examples": ["政府推出許多用稻米製作的點心食譜，以鼓勵國民多多食用。"]},
            {"word": "蘿蔔糕", "examples": ["過年時媽媽總會買塊蘿蔔糕，以討個好采頭。"]},
            {"word": "米漿", "examples": ["一杯米漿，一根油條，就是他多年來固定不變的早餐。"]},
            {"word": "發財", "examples": ["他為了發財，不惜從事投機事業。", "您最近在哪兒發財？"]},
            {"word": "艾草", "examples": []},
            {"word": "健康", "examples": ["健康就是人生最大的財富。"]},
            {"word": "粽子", "examples": []},
            {"word": "推陳出新", "examples": ["本公司的產品要不斷的推陳出新，以迎合顧客的需求。"]},
        ],
    },
    5: {
        "title": "讀書報告-藍色小洋裝",
        "characters": [
            {"char": "籍", "similar_wrong": ["集", "級", "急", "即", "及"], "examples": []},
            {"char": "繪", "similar_wrong": ["慧", "會"], "examples": []},
            {"char": "版", "similar_wrong": ["板"], "examples": ["今天的報紙共有十六版。", "這本書已出至十二版。"]},
            {"char": "介", "similar_wrong": ["屆", "借", "界", "届", "戒"], "examples": []},
            {"char": "峽", "similar_wrong": ["狹"], "examples": []},
            {"char": "玉", "similar_wrong": ["欲", "獄", "遇", "預", "域"], "examples": ["這件事多謝您的玉成。"]},
            {"char": "泣", "similar_wrong": ["棄", "氣", "契"], "examples": []},
            {"char": "敏", "similar_wrong": ["民"], "examples": []},
            {"char": "癢", "similar_wrong": ["仰", "養"], "examples": ["那推銷員的三寸不爛之舌，說得她心癢癢的，差點就買了他介紹的產品。"]},
            {"char": "麥", "similar_wrong": ["邁", "賣", "脈"], "examples": []},
            {"char": "封", "similar_wrong": ["豐", "蜂", "峰", "楓", "風"], "examples": []},
            {"char": "淺", "similar_wrong": ["千", "乾", "潛"], "examples": []},
            {"char": "查", "similar_wrong": ["茶", "察"], "examples": []},
            {"char": "酵", "similar_wrong": ["教", "叫"], "examples": []},
            {"char": "讚", "similar_wrong": ["暫", "贊"], "examples": []},
        ],
        "compounds": [
            {"word": "書籍", "examples": ["王教授將他生平珍愛的一些書籍捐贈給圖書館。"]},
            {"word": "出版", "examples": ["這位作家的新作即將出版，預約可享八折優待。"]},
            {"word": "簡介", "examples": ["一般國家公園多備有手冊，簡介園內的環境和歷史。"]},
            {"word": "哭泣", "examples": ["他個性堅強，遇到挫折從不哭泣。"]},
            {"word": "過敏", "examples": ["藥物過敏、花粉過敏", "他一向神經過敏，別人的一句閒話就會使他煩惱半天。"]},
            {"word": "發癢", "examples": ["他因皮膚過敏而全身發癢。", "她看見自己喜愛的物品卻無力購買時，心裡直發癢。"]},
            {"word": "麥芽糖", "examples": ["糖葫蘆外面裹著一層麥芽糖，甜甜的，是小孩子喜歡的零食。"]},
            {"word": "封面", "examples": ["這本書的封面設計很別緻。"]},
            {"word": "發酵", "examples": ["酵母菌行發酵作用時，可以將糖分解為酒精和二氧化碳。"]},
            {"word": "讚嘆", "examples": ["面對尼加拉瀑布的壯麗景觀，我不禁讚嘆大自然的奧妙神奇。"]},
        ],
    },
    6: {
        "title": "我愛鹿港",
        "characters": [
            {"char": "插", "similar_wrong": ["叉"], "examples": []},
            {"char": "拌", "similar_wrong": ["辦", "伴", "半", "絆"], "examples": ["這兩人拌嘴是司空見慣的。"]},
            {"char": "磚", "similar_wrong": ["專"], "examples": []},
            {"char": "昂", "similar_wrong": ["骯"], "examples": []},
            {"char": "繁", "similar_wrong": ["凡", "煩"], "examples": []},
            {"char": "葫", "similar_wrong": ["壺", "湖", "糊"], "examples": ["這葫蘆香包好可愛。"]},
            {"char": "蘆", "similar_wrong": ["爐"], "examples": []},
            {"char": "彎", "similar_wrong": ["丸", "萬", "完"], "examples": []},
            {"char": "狹", "similar_wrong": ["峽"], "examples": []},
            {"char": "窄", "similar_wrong": ["摘", "宅"], "examples": []},
            {"char": "喻", "similar_wrong": ["遇", "玉", "欲", "域", "預"], "examples": []},
            {"char": "曉", "similar_wrong": ["小"], "examples": []},
            {"char": "井", "similar_wrong": ["景", "警"], "examples": []},
            {"char": "芬", "similar_wrong": ["分"], "examples": []},
            {"char": "芳", "similar_wrong": ["坊", "方"], "examples": []},
        ],
        "compounds": [
            {"word": "穿插", "examples": ["在一大束紅玫瑰中穿插一些白色的滿天星，別具一番風貌。", "這部戰爭片穿插著淒美的愛情故事。"]},
            {"word": "紅磚", "examples": ["我老家的房子，是用一塊塊的紅磚砌成的。"]},
            {"word": "昂貴", "examples": ["進口的名牌貨品價格都比較昂貴。"]},
            {"word": "繁榮", "examples": ["由於財經策略運用成功，臺灣經濟日益繁榮。"]},
            {"word": "葫蘆", "examples": ["爸爸將成熟的葫蘆晒乾後剖開挖空，製成水瓢。"]},
            {"word": "彎彎曲曲", "examples": ["這條山路彎彎曲曲，非常難走。"]},
            {"word": "狹窄", "examples": ["自從那條狹窄的外環道路拓寬後，塞車的狀況改善不少。", "心地狹窄的人很難過著輕鬆快樂的生活。"]},
            {"word": "家喻戶曉", "examples": ["她是家喻戶曉的大明星，因此一舉一動都格外引人注目。"]},
            {"word": "芬芳", "examples": ["百花競吐芬芳。", "他的人格高尚，德性芬芳，足以為人楷模。"]},
        ],
    },
    7: {
        "title": "未來的模樣",
        "characters": [
            {"char": "跡", "similar_wrong": ["機", "擊", "積", "基", "饑"], "examples": []},
            {"char": "移", "similar_wrong": ["儀", "姨", "遺", "宜", "怡"], "examples": []},
            {"char": "搭", "similar_wrong": ["達", "打", "答"], "examples": []},
            {"char": "輸", "similar_wrong": ["舒", "疏", "殊", "蔬", "梳"], "examples": []},
            {"char": "鍵", "similar_wrong": ["劍", "賤", "健", "見", "建"], "examples": []},
            {"char": "盤", "similar_wrong": ["攀", "判"], "examples": []},
            {"char": "饑", "similar_wrong": ["雞", "積", "跡", "機", "基"], "examples": []},
            {"char": "荒", "similar_wrong": ["慌"], "examples": []},
            {"char": "配", "similar_wrong": ["佩"], "examples": []},
            {"char": "均", "similar_wrong": ["君"], "examples": []},
            {"char": "遷", "similar_wrong": ["鉛", "千"], "examples": []},
            {"char": "致", "similar_wrong": ["智", "秩", "志", "至", "質"], "examples": []},
            {"char": "惡", "similar_wrong": ["餓"], "examples": []},
            {"char": "攜", "similar_wrong": ["鞋", "協", "斜"], "examples": []},
            {"char": "眨", "similar_wrong": ["扎", "炸"], "examples": []},
        ],
        "compounds": [
            {"word": "足跡", "examples": ["沙灘上印下我們相偕走過的足跡。"]},
            {"word": "移動", "examples": ["他很不喜歡別人隨便移動書房中的文物。"]},
            {"word": "傳輸", "examples": ["此地設備落伍，傳輸緩慢，因此所能取得的資訊有限。"]},
            {"word": "鍵盤", "examples": ["她的琴藝高超，只見手指在鍵盤上靈活的躍動，美妙的音樂就流瀉而出。"]},
            {"word": "饑荒", "examples": ["非洲地區土地貧瘠，氣候不良，因此常鬧饑荒。"]},
            {"word": "分配", "examples": ["各種能源都應該合理分配運用。"]},
            {"word": "平均", "examples": ["這次聚餐的費用，是由參與的同學平均分攤。"]},
            {"word": "變遷", "examples": ["世事的變遷常令人有滄海桑田的感覺。"]},
            {"word": "導致", "examples": ["他們夫妻倆因長期溝通不良而導致分手。"]},
            {"word": "惡化", "examples": ["病情惡化、水質惡化"]},
            {"word": "攜手", "examples": ["經過多年的愛情長跑，他們終於決定攜手共度未來。"]},
        ],
    },
    8: {
        "title": "動物老師的智慧",
        "characters": [
            {"char": "眾", "similar_wrong": ["重"], "examples": []},
            {"char": "領", "similar_wrong": ["嶺"], "examples": []},
            {"char": "獨", "similar_wrong": ["毒", "讀"], "examples": []},
            {"char": "厚", "similar_wrong": ["候", "后"], "examples": []},
            {"char": "蹼", "similar_wrong": ["普", "譜"], "examples": []},
            {"char": "趾", "similar_wrong": ["止", "紙", "只", "指"], "examples": []},
            {"char": "膜", "similar_wrong": ["磨", "模", "摩", "魔"], "examples": []},
            {"char": "構", "similar_wrong": ["購", "夠"], "examples": []},
            {"char": "潛", "similar_wrong": ["前", "乾", "錢"], "examples": []},
            {"char": "易", "similar_wrong": ["異", "益", "亦", "義", "役"], "examples": []},
            {"char": "壁", "similar_wrong": ["閉", "避", "畢", "必"], "examples": []},
            {"char": "舉", "similar_wrong": ["懼", "巨", "居"], "examples": []},
            {"char": "究", "similar_wrong": ["救", "舊", "九"], "examples": []},
            {"char": "肢", "similar_wrong": ["脂", "蜘", "枝", "知", "隻"], "examples": []},
            {"char": "絕", "similar_wrong": ["覺"], "examples": []},
        ],
        "compounds": [
            {"word": "與眾不同", "examples": ["他喜歡標新立異，連穿著也與眾不同。"]},
            {"word": "看家本領", "examples": ["短打觸擊是中華隊的看家本領，使得對方守備陣容大亂。"]},
            {"word": "得天獨厚", "examples": ["她有一副得天獨厚的好嗓子，因此一出道便大受歡迎。"]},
            {"word": "腳趾", "examples": ["她因為走了太多路，腳趾上都起了水泡。"]},
            {"word": "構造", "examples": ["人體的構造非常精妙，非人工技術所能模擬。"]},
            {"word": "輕易", "examples": ["這不是件輕易的事，大家要先有心理準備。"]},
            {"word": "壁虎", "examples": ["壁虎的尾部尖長，遇到敵襲時常自斷逃生。"]},
            {"word": "輕而易舉", "examples": ["對他而言，這件事輕而易舉，難不倒他的。"]},
            {"word": "研究", "examples": ["老師要同學們種植綠豆，以研究它的生長過程。"]},
            {"word": "肢體", "examples": ["他雖然肢體稍有殘缺，但毅力卻比一般人還要堅定。"]},
            {"word": "身懷絕技", "examples": ["這部武俠片的主角，個個都是身懷絕技、功夫了得的武林高手。"]},
        ],
    },
    9: {
        "title": "向太空出發",
        "characters": [
            {"char": "僅", "similar_wrong": ["盡"], "examples": []},
            {"char": "號", "similar_wrong": ["耗"], "examples": []},
            {"char": "姆", "similar_wrong": ["母"], "examples": []},
            {"char": "斯", "similar_wrong": ["司", "思", "私", "絲"], "examples": []},
            {"char": "仍", "similar_wrong": ["扔"], "examples": []},
            {"char": "津", "similar_wrong": ["今", "筋", "金", "斤"], "examples": []},
            {"char": "嘗", "similar_wrong": ["常", "腸", "嫦"], "examples": []},
            {"char": "試", "similar_wrong": ["市", "是", "釋", "示", "士"], "examples": []},
            {"char": "測", "similar_wrong": ["側", "冊", "廁", "策"], "examples": []},
            {"char": "署", "similar_wrong": ["暑", "鼠", "屬"], "examples": []},
            {"char": "億", "similar_wrong": ["亦", "益", "易", "憶", "役"], "examples": []},
            {"char": "翁", "similar_wrong": ["嗡", "蓊"], "examples": []},
            {"char": "嚮", "similar_wrong": ["向", "像", "巷", "象"], "examples": []},
            {"char": "引", "similar_wrong": ["隱", "飲", "蚓"], "examples": []},
            {"char": "催", "similar_wrong": ["脆", "翠"], "examples": []},
        ],
        "compounds": [
            {"word": "不僅", "examples": ["這不僅是他個人的意思，也是全體同學的想法。"]},
            {"word": "阿姆斯壯", "examples": []},
            {"word": "津津樂道", "examples": ["當年小王見義勇為、捨身救人的事蹟，至今仍為眾人津津樂道。"]},
            {"word": "嘗試", "examples": ["在還沒確定自己的志向前，不妨多方嘗試一下。"]},
            {"word": "探測", "examples": []},
            {"word": "太空總署", "examples": []},
            {"word": "大富翁", "examples": ["他希望有朝一日能成為世界數一數二的大富翁。"]},
            {"word": "嚮往", "examples": ["桃花源的生活令人嚮往。"]},
            {"word": "吸引", "examples": ["這家餐廳打算重新整修裝潢以吸引顧客上門。"]},
            {"word": "催生", "examples": ["產婦若羊水已破，需立即催生。"]},
        ],
    },
    10: {
        "title": "小青蛙想看海",
        "characters": [
            {"char": "豪", "similar_wrong": ["毫"], "examples": []},
            {"char": "忽", "similar_wrong": ["乎", "呼"], "examples": []},
            {"char": "瞧", "similar_wrong": ["橋", "喬"], "examples": []},
            {"char": "灘", "similar_wrong": ["痰", "嘆", "坦"], "examples": []},
            {"char": "苔", "similar_wrong": ["臺", "抬", "颱", "台"], "examples": []},
            {"char": "滾", "similar_wrong": ["棍"], "examples": []},
            {"char": "禁", "similar_wrong": ["近", "進"], "examples": []},
            {"char": "際", "similar_wrong": ["技", "繼", "既", "紀", "季"], "examples": []},
            {"char": "廣", "similar_wrong": ["光", "逛"], "examples": []},
            {"char": "丈", "similar_wrong": ["帳"], "examples": []},
            {"char": "災", "similar_wrong": ["在", "再"], "examples": []},
            {"char": "旱", "similar_wrong": ["漢", "汗", "憾"], "examples": []},
            {"char": "耗", "similar_wrong": ["號"], "examples": []},
            {"char": "遺", "similar_wrong": ["儀", "姨", "疑", "移", "怡"], "examples": []},
            {"char": "憾", "similar_wrong": ["漢", "汗", "旱"], "examples": []},
        ],
        "compounds": [
            {"word": "自豪", "examples": ["他對自己的廚藝頗為自豪。"]},
            {"word": "忽然", "examples": ["忽然間烏雲密布，緊接著就下起大雨來了。"]},
            {"word": "打滾", "examples": ["小狗在沙堆裡打滾玩耍。"]},
            {"word": "禁不住", "examples": ["她的身子一向嬌弱，禁不住這種變化無常的天氣。"]},
            {"word": "一望無際", "examples": ["登上樓頂，是一望無際的藍天白雲，頓時感覺神清氣爽。"]},
            {"word": "寬廣", "examples": ["新闢的公園占地寬廣，公共設施相當完善，是休閒的好去處。"]},
            {"word": "萬丈", "examples": []},
            {"word": "水災", "examples": ["連日的豪雨，已使各地水災頻傳。"]},
            {"word": "旱災", "examples": ["因為缺水而造成的旱災，可望由連日的豪雨而解除。"]},
            {"word": "耗盡", "examples": ["他們為了醫治因車禍而癱瘓的兒子，幾已耗盡家產。"]},
            {"word": "遺憾", "examples": ["膝下無子是他終身的遺憾。"]},
        ],
    },
    11: {
        "title": "窗前的月光",
        "characters": [
            {"char": "皎", "similar_wrong": ["角", "腳", "繳"], "examples": []},
            {"char": "瘦", "similar_wrong": ["售", "受", "授"], "examples": []},
            {"char": "嫦", "similar_wrong": ["嘗", "常", "腸"], "examples": []},
            {"char": "娥", "similar_wrong": ["額", "鵝"], "examples": []},
            {"char": "搗", "similar_wrong": ["導", "島"], "examples": []},
            {"char": "吳", "similar_wrong": ["吾"], "examples": []},
            {"char": "霜", "similar_wrong": ["雙"], "examples": []},
            {"char": "映", "similar_wrong": ["硬"], "examples": []},
            {"char": "勾", "similar_wrong": ["溝"], "examples": []},
            {"char": "浮", "similar_wrong": ["服", "佛", "蝠", "幅"], "examples": []},
            {"char": "盞", "similar_wrong": ["展"], "examples": []},
            {"char": "否", "similar_wrong": ["斧", "腐", "釜"], "examples": []},
            {"char": "舊", "similar_wrong": ["就", "救"], "examples": []},
            {"char": "淚", "similar_wrong": ["類"], "examples": []},
            {"char": "孤", "similar_wrong": ["箍", "估", "姑"], "examples": []},
        ],
        "compounds": [
            {"word": "皎潔", "examples": ["今晚的月色分外皎潔。"]},
            {"word": "嫦娥", "examples": []},
            {"word": "吳剛", "examples": []},
            {"word": "冰霜", "examples": []},
            {"word": "映照", "examples": ["湖面在夕陽映照下，水光粼粼，煞是美麗。"]},
            {"word": "浮現", "examples": ["見到眼前的景象，十幾年前的往事一一浮現心頭。"]},
            {"word": "是否", "examples": ["老師問我們是否讀過一些偉人傳記？"]},
            {"word": "依舊", "examples": ["景物依舊，人事已非。"]},
            {"word": "淚水", "examples": ["天然的淚水具有消毒、淨化、潤溼眼球的功能。"]},
            {"word": "孤單", "examples": ["由於父母忙於工作，那個小孩常孤單一人在住家附近遊盪。"]},
        ],
    },
    12: {
        "title": "如來佛的手掌心",
        "characters": [
            {"char": "乖", "similar_wrong": ["拐", "怪"], "examples": []},
            {"char": "筋", "similar_wrong": ["今", "金", "斤", "津"], "examples": []},
            {"char": "斗", "similar_wrong": ["豆"], "examples": []},
            {"char": "箍", "similar_wrong": ["估", "姑", "孤"], "examples": []},
            {"char": "喚", "similar_wrong": ["患", "換", "幻"], "examples": []},
            {"char": "掀", "similar_wrong": ["鮮", "先", "仙"], "examples": []},
            {"char": "修", "similar_wrong": ["休"], "examples": []},
            {"char": "咒", "similar_wrong": ["宙", "皺"], "examples": []},
            {"char": "橘", "similar_wrong": ["局"], "examples": []},
            {"char": "擋", "similar_wrong": ["當", "檔", "盪"], "examples": []},
            {"char": "掏", "similar_wrong": ["討", "套", "逃"], "examples": []},
            {"char": "齊", "similar_wrong": ["奇", "旗", "其", "騎"], "examples": []},
            {"char": "聖", "similar_wrong": ["勝", "剩", "盛"], "examples": []},
            {"char": "砰", "similar_wrong": ["朋", "碰", "捧"], "examples": []},
            {"char": "壓", "similar_wrong": ["鴨"], "examples": []},
        ],
        "compounds": [
            {"word": "乖乖", "examples": ["乖乖！這師傅的手藝還真不賴！"]},
            {"word": "筋斗雲", "examples": []},
            {"word": "金箍棒", "examples": []},
            {"word": "呼風喚雨", "examples": ["民間傳說裡的道士既能呼風喚雨，又能驅邪除魔。"]},
            {"word": "掀翻", "examples": ["他與對方談判破裂，憤而掀翻桌子。"]},
            {"word": "修行", "examples": ["他是一位在家修行的居士。"]},
            {"word": "咒語", "examples": ["法會上，法師口唸咒語，超渡亡魂。"]},
            {"word": "掏出", "examples": []},
            {"word": "齊天大聖", "examples": []},
            {"word": "壓住", "examples": ["風太大了！拿本書把桌上的紙張壓住吧！"]},
        ],
    },
}

# ---------- 二下-翰林版 ----------

VOCAB_DATA_GRADE2 = {
    1: {
        "title": "種子旅行真奇妙",
        "characters": [
            {"char": "旅", "similar_wrong": ["呂"], "examples": []},
            {"char": "行", "similar_wrong": ["型"], "examples": []},
            {"char": "妙", "similar_wrong": ["廟"], "examples": []},
            {"char": "公", "similar_wrong": ["供", "恭", "宮", "攻", "功"], "examples": []},
            {"char": "園", "similar_wrong": ["源", "原", "圓", "元", "緣"], "examples": []},
            {"char": "針", "similar_wrong": ["偵", "珍", "真"], "examples": []},
            {"char": "尖", "similar_wrong": ["間", "兼", "肩", "監", "堅"], "examples": []},
            {"char": "狗", "similar_wrong": ["勾", "夠", "構"], "examples": []},
            {"char": "士", "similar_wrong": ["拭", "示", "市", "似", "勢"], "examples": []},
            {"char": "貓", "similar_wrong": ["茂", "冒", "貌"], "examples": []},
            {"char": "探", "similar_wrong": ["嘆"], "examples": []},
            {"char": "險", "similar_wrong": ["鮮", "現", "憲"], "examples": []},
            {"char": "黑", "similar_wrong": ["嘿", "赫"], "examples": []},
            {"char": "傘", "similar_wrong": ["三"], "examples": []},
            {"char": "由", "similar_wrong": ["尤", "游", "遊", "油"], "examples": []},
            {"char": "哇", "similar_wrong": ["蛙", "挖", "娃"], "examples": []},
            {"char": "世", "similar_wrong": ["釋", "是", "勢", "似", "室"], "examples": []},
            {"char": "界", "similar_wrong": ["屆", "借", "介", "届", "戒"], "examples": []},
            {"char": "鬼", "similar_wrong": ["桂", "龜", "櫃"], "examples": []},
            {"char": "刺", "similar_wrong": ["賜", "次"], "examples": []},
            {"char": "昭", "similar_wrong": ["招"], "examples": []},
            {"char": "飛", "similar_wrong": ["非"], "examples": []},
        ],
        "compounds": [
            {"word": "旅行", "examples": ["旅行不但可以調劑身心，還能增廣見聞。"]},
            {"word": "奇妙", "examples": ["許多動物都有預知危險的本能，上帝造物真是奇妙。"]},
            {"word": "公園", "examples": ["陽明山國家公園的花季，每年都吸引大批的賞花人潮。"]},
            {"word": "鬼針草", "examples": []},
            {"word": "巴士", "examples": ["公共巴士、遊覽巴士　◎。"]},
            {"word": "探險", "examples": ["他經常夢想去南極探險。"]},
            {"word": "昭和草", "examples": []},
            {"word": "自由", "examples": ["自由是幸福的基礎，不自由，即無快樂與幸福可言。"]},
            {"word": "世界", "examples": ["大千世界、浮華世界。"]},
        ],
    },
    2: {
        "title": "小水滴愛上探險",
        "characters": [
            {"char": "滴", "similar_wrong": ["低"], "examples": []},
            {"char": "躺", "similar_wrong": ["堂", "塘", "湯"], "examples": []},
            {"char": "次", "similar_wrong": ["賜", "刺"], "examples": []},
            {"char": "落", "similar_wrong": ["駱", "絡"], "examples": []},
            {"char": "荷", "similar_wrong": ["和", "核", "合", "何", "河"], "examples": []},
            {"char": "珍", "similar_wrong": ["偵", "針", "真"], "examples": []},
            {"char": "珠", "similar_wrong": ["蛛", "豬", "朱"], "examples": []},
            {"char": "第", "similar_wrong": ["弟", "地", "帝"], "examples": []},
            {"char": "被", "similar_wrong": ["背", "貝", "備", "倍"], "examples": []},
            {"char": "轉", "similar_wrong": ["磚", "專", "賺"], "examples": []},
            {"char": "甩", "similar_wrong": ["帥"], "examples": []},
            {"char": "浪", "similar_wrong": ["狼"], "examples": []},
            {"char": "救", "similar_wrong": ["就", "舊"], "examples": []},
            {"char": "植", "similar_wrong": ["值", "直", "職"], "examples": []},
            {"char": "提", "similar_wrong": ["題"], "examples": []},
            {"char": "漠", "similar_wrong": ["末", "默", "墨"], "examples": []},
            {"char": "令", "similar_wrong": ["另"], "examples": []},
            {"char": "及", "similar_wrong": ["即", "級", "急", "疾", "集"], "examples": []},
            {"char": "滾", "similar_wrong": ["棍"], "examples": []},
        ],
        "compounds": [
            {"word": "水滴", "examples": ["陣雨過後，水滴沿著屋簷掉落下來。"]},
            {"word": "珍珠", "examples": ["珍珠項鍊　△真珠。"]},
            {"word": "海浪", "examples": ["海浪洶湧，非常壯觀。"]},
            {"word": "植物", "examples": ["植物具有綠化環境、淨化空氣的功能。"]},
            {"word": "提起", "examples": ["他提起公事包，匆匆忙忙的趕去上班。"]},
            {"word": "沙漠", "examples": ["沙漠地區日夜的溫差極大。"]},
            {"word": "等不及", "examples": ["他猶豫再三，還是不肯開口說話，大家都等不及了。"]},
        ],
    },
    3: {
        "title": "紫斑蝶向北飛",
        "characters": [
            {"char": "紫", "similar_wrong": ["姊"], "examples": []},
            {"char": "北", "similar_wrong": ["備", "悲", "杯"], "examples": []},
            {"char": "悄", "similar_wrong": ["瞧", "巧", "橋"], "examples": []},
            {"char": "擔", "similar_wrong": ["丹", "單"], "examples": []},
            {"char": "翅", "similar_wrong": ["持", "遲", "恥"], "examples": []},
            {"char": "膀", "similar_wrong": ["綁"], "examples": []},
            {"char": "讓", "similar_wrong": ["壤", "嚷"], "examples": []},
            {"char": "溜", "similar_wrong": ["柳", "流", "六"], "examples": []},
            {"char": "滑", "similar_wrong": ["話", "花", "劃"], "examples": []},
            {"char": "梯", "similar_wrong": ["踢"], "examples": []},
            {"char": "碰", "similar_wrong": ["彭", "砰", "捧"], "examples": []},
            {"char": "遇", "similar_wrong": ["預", "欲", "玉", "獄", "喻"], "examples": []},
            {"char": "鳥", "similar_wrong": ["尿"], "examples": []},
            {"char": "終", "similar_wrong": ["鐘", "中", "忠"], "examples": []},
            {"char": "於", "similar_wrong": ["余", "漁", "于", "愚", "魚"], "examples": []},
            {"char": "木", "similar_wrong": ["幕", "目", "暮", "牧"], "examples": []},
            {"char": "些", "similar_wrong": ["鞋", "協", "寫"], "examples": []},
            {"char": "伴", "similar_wrong": ["拌", "辦", "半", "絆"], "examples": []},
            {"char": "斑", "similar_wrong": ["班", "搬"], "examples": []},
            {"char": "蝶", "similar_wrong": ["碟", "疊"], "examples": []},
            {"char": "盪", "similar_wrong": ["檔"], "examples": []},
        ],
        "compounds": [
            {"word": "悄悄", "examples": ["他躡著腳悄悄的進門，深怕驚醒了睡夢中的父親。"]},
            {"word": "擔心", "examples": ["外出時要記得告訴父母親，免得他們擔心。"]},
            {"word": "翅膀", "examples": ["企鵝的翅膀雖然無法飛行，但在水中卻有划水的功能。"]},
            {"word": "滑梯", "examples": ["爺爺常帶妹妹到公園去溜滑梯。"]},
            {"word": "終於", "examples": ["經過多次試驗後，太空梭終於發射成功。"]},
            {"word": "樹木", "examples": ["道路兩旁的樹木被颱風吹得東倒西歪。"]},
            {"word": "這些", "examples": ["這些東西是她在折扣期間買的。"]},
            {"word": "同伴", "examples": ["登山時，最好能多邀幾個同伴一起去，彼此也好照應。"]},
        ],
    },
    4: {
        "title": "一場雨",
        "characters": [
            {"char": "場", "similar_wrong": ["廠"], "examples": []},
            {"char": "農", "similar_wrong": ["弄"], "examples": []},
            {"char": "夫", "similar_wrong": ["孵"], "examples": []},
            {"char": "渴", "similar_wrong": ["可"], "examples": []},
            {"char": "稻", "similar_wrong": ["盜", "倒", "道", "到"], "examples": []},
            {"char": "喝", "similar_wrong": ["呵"], "examples": []},
            {"char": "飽", "similar_wrong": ["保", "堡", "寶"], "examples": []},
            {"char": "洗", "similar_wrong": ["喜"], "examples": []},
            {"char": "蚯", "similar_wrong": ["秋"], "examples": []},
            {"char": "蚓", "similar_wrong": ["隱", "飲", "引"], "examples": []},
            {"char": "扭", "similar_wrong": ["牛"], "examples": []},
            {"char": "尾", "similar_wrong": ["偉", "委", "葦"], "examples": []},
            {"char": "泥", "similar_wrong": ["尼"], "examples": []},
            {"char": "蝌", "similar_wrong": ["棵", "科"], "examples": []},
            {"char": "蚪", "similar_wrong": ["都", "斗", "豆"], "examples": []},
            {"char": "努", "similar_wrong": ["怒"], "examples": []},
            {"char": "爺", "similar_wrong": ["葉", "也", "頁"], "examples": []},
            {"char": "剛", "similar_wrong": ["鋼", "缸", "綱"], "examples": []},
            {"char": "淹", "similar_wrong": ["煙"], "examples": []},
        ],
        "compounds": [
            {"word": "農夫", "examples": ["這些蔬菜都是農夫在田裡流汗的成果，我們不應該浪費。"]},
            {"word": "口渴", "examples": ["在大太陽底下走了一天的路，他感到非常口渴。"]},
            {"word": "稻子", "examples": ["這些稻子將送往工廠碾成食米銷售。"]},
            {"word": "洗澡", "examples": ["爸爸每天回家後都會先洗澡，再吃晚飯。"]},
            {"word": "蚯蚓", "examples": ["蚯蚓能夠分解腐土，有利於農作物的成長。", "△地龍　◎。"]},
            {"word": "尾巴", "examples": ["狗尾巴、飛機尾巴。"]},
            {"word": "淹水", "examples": ["都市的排水系統若不健全，下雨時便容易淹水。"]},
            {"word": "泥巴", "examples": ["他從小就愛玩泥巴，如今已成一位有名的雕塑家。"]},
            {"word": "蝌蚪", "examples": ["老師要學生飼養蝌蚪，並且加以觀察和記錄它的生長狀態。", "△科斗、蝌子、懸針◎。"]},
            {"word": "努力", "examples": ["努力讀書、努力奮鬥。"]},
            {"word": "老天爺", "examples": ["希望老天爺保佑我早日尋回失蹤的女兒。"]},
            {"word": "剛好", "examples": ["這件衣服穿在你身上，真是剛好不過了。"]},
        ],
    },
    5: {
        "title": "笑容回來了",
        "characters": [
            {"char": "容", "similar_wrong": ["榮", "蓉"], "examples": []},
            {"char": "丟", "similar_wrong": ["去", "丢"], "examples": []},
            {"char": "負", "similar_wrong": ["複", "富", "覆", "父", "復"], "examples": []},
            {"char": "責", "similar_wrong": ["則", "擇", "澤"], "examples": []},
            {"char": "收", "similar_wrong": ["瘦", "受", "授"], "examples": []},
            {"char": "漸", "similar_wrong": ["件", "賤", "見", "建", "健"], "examples": []},
            {"char": "臉", "similar_wrong": ["練", "聯", "戀"], "examples": []},
            {"char": "雖", "similar_wrong": ["碎", "歲", "隧"], "examples": []},
            {"char": "換", "similar_wrong": ["患", "幻", "喚"], "examples": []},
            {"char": "工", "similar_wrong": ["公", "宮", "恭", "攻", "功"], "examples": []},
            {"char": "總", "similar_wrong": ["宗", "粽"], "examples": []},
            {"char": "親", "similar_wrong": ["侵"], "examples": []},
            {"char": "切", "similar_wrong": ["且"], "examples": []},
            {"char": "慢", "similar_wrong": ["漫"], "examples": []},
            {"char": "利", "similar_wrong": ["力", "粒", "立", "歷", "厲"], "examples": []},
            {"char": "合", "similar_wrong": ["和", "核", "荷", "何", "河"], "examples": []},
            {"char": "式", "similar_wrong": ["拭", "似", "是", "室", "氏"], "examples": []},
            {"char": "露", "similar_wrong": ["錄", "陸", "鹿"], "examples": []},
            {"char": "亂", "similar_wrong": ["卵", "巒"], "examples": []},
            {"char": "資", "similar_wrong": ["姿"], "examples": []},
            {"char": "源", "similar_wrong": ["原", "圓", "元", "園", "緣"], "examples": []},
            {"char": "謝", "similar_wrong": ["斜", "協", "寫"], "examples": []},
            {"char": "微", "similar_wrong": ["危", "威"], "examples": []},
        ],
        "compounds": [
            {"word": "笑容", "examples": ["笑容滿面、面帶笑容。"]},
            {"word": "負責", "examples": ["他在報社負責編輯工作。"]},
            {"word": "資源回收", "examples": []},
            {"word": "漸漸", "examples": ["這個星期三開始，天氣會漸漸好轉，氣溫也會回升。"]},
            {"word": "雖然", "examples": ["雖然這件工作很辛苦，但對年輕人來說是一個很好的磨鍊。"]},
            {"word": "工作", "examples": ["他熱愛導遊的工作。"]},
            {"word": "總是", "examples": ["他做事總是慢吞吞的。"]},
            {"word": "親切", "examples": ["她因為待人親切，所以人緣極佳。"]},
            {"word": "慢慢", "examples": ["你先冷靜下來，聽我慢慢的將事情說清楚。"]},
            {"word": "利用", "examples": ["廢物利用。"]},
            {"word": "合作", "examples": ["在大家通力合作下，這項艱鉅的工作終於完成了。"]},
            {"word": "謝謝", "examples": []},
            {"word": "微笑", "examples": ["微笑是通行世界各地，最好的溝通語言。"]},
            {"word": "方式", "examples": ["表演方式、工作方式。"]},
            {"word": "露出", "examples": ["他露出猶豫的臉色，不知道該不該答應對方的要求。"]},
        ],
    },
    6: {
        "title": "好好的說話",
        "characters": [
            {"char": "從", "similar_wrong": ["叢"], "examples": []},
            {"char": "臺", "similar_wrong": ["抬", "颱", "苔", "台"], "examples": []},
            {"char": "夠", "similar_wrong": ["構", "購"], "examples": []},
            {"char": "昨", "similar_wrong": ["作", "左", "佐"], "examples": []},
            {"char": "球", "similar_wrong": ["求"], "examples": []},
            {"char": "捧", "similar_wrong": ["砰", "朋", "碰"], "examples": []},
            {"char": "腹", "similar_wrong": ["附", "負", "復", "複", "覆"], "examples": []},
            {"char": "告", "similar_wrong": ["高", "糕"], "examples": []},
            {"char": "訴", "similar_wrong": ["素", "宿"], "examples": []},
            {"char": "整", "similar_wrong": ["證", "征", "爭"], "examples": []},
            {"char": "廁", "similar_wrong": ["側", "冊", "策", "測"], "examples": []},
            {"char": "所", "similar_wrong": ["索"], "examples": []},
            {"char": "踢", "similar_wrong": ["梯"], "examples": []},
            {"char": "足", "similar_wrong": ["族", "卒"], "examples": []},
            {"char": "比", "similar_wrong": ["彼", "筆"], "examples": []},
            {"char": "校", "similar_wrong": ["笑", "效", "孝"], "examples": []},
            {"char": "信", "similar_wrong": ["欣", "心", "新"], "examples": []},
            {"char": "祝", "similar_wrong": ["注", "住", "柱", "著", "助"], "examples": []},
            {"char": "搬", "similar_wrong": ["班", "斑"], "examples": []},
            {"char": "禮", "similar_wrong": ["李", "裡", "里", "理"], "examples": []},
            {"char": "貌", "similar_wrong": ["茂", "冒"], "examples": []},
        ],
        "compounds": [
            {"word": "自從", "examples": ["自從上次慘遭車禍之後，他再也不敢開快車了。"]},
            {"word": "能夠", "examples": ["今天能夠做完的事，不要拖到明天。"]},
            {"word": "昨天", "examples": ["他昨天淋雨回來，今天就覺得身體不太舒服了。"]},
            {"word": "捧腹大笑", "examples": ["他言談詼諧，常令人捧腹大笑。"]},
            {"word": "告訴", "examples": ["他因為土地被侵占，而向法院提出告訴。"]},
            {"word": "完整", "examples": ["問答題的作答應力求完整，才能獲得高分。"]},
            {"word": "廁所", "examples": ["爸爸每天早晨起床第一件事，就是帶著報紙進廁所。"]},
            {"word": "足球", "examples": ["在所有的運動中，他最喜歡足球。"]},
            {"word": "禮貌", "examples": ["她見到鄰居、長輩都會點頭含笑的打招呼，非常有禮貌。"]},
            {"word": "學校", "examples": ["學校是培育人才的搖籃。"]},
        ],
    },
    7: {
        "title": "色彩變變變",
        "characters": [
            {"char": "調", "similar_wrong": ["掉"], "examples": []},
            {"char": "盤", "similar_wrong": ["攀", "判"], "examples": []},
            {"char": "配", "similar_wrong": ["佩"], "examples": []},
            {"char": "藍", "similar_wrong": ["籃", "欄"], "examples": []},
            {"char": "顏", "similar_wrong": ["言", "炎", "嚴", "研"], "examples": []},
            {"char": "魔", "similar_wrong": ["磨", "模", "膜", "摩"], "examples": []},
            {"char": "料", "similar_wrong": ["療", "聊"], "examples": []},
            {"char": "幾", "similar_wrong": ["擠", "己"], "examples": []},
            {"char": "已", "similar_wrong": ["乙", "蟻", "以"], "examples": []},
            {"char": "經", "similar_wrong": ["驚", "精", "京", "睛", "鯨"], "examples": []},
            {"char": "趣", "similar_wrong": ["去"], "examples": []},
            {"char": "呵", "similar_wrong": ["喝"], "examples": []},
            {"char": "將", "similar_wrong": ["江", "漿"], "examples": []},
            {"char": "混", "similar_wrong": ["婚", "昏"], "examples": []},
            {"char": "橙", "similar_wrong": ["成", "城", "乘", "呈", "誠"], "examples": []},
            {"char": "棒", "similar_wrong": ["幫", "綁", "膀"], "examples": []},
            {"char": "神", "similar_wrong": ["什"], "examples": []},
        ],
        "compounds": [
            {"word": "調色盤", "examples": ["他手拿調色盤，將眼前的美景細細繪下。"]},
            {"word": "顏色", "examples": ["美麗的彩虹一共有七種顏色。"]},
            {"word": "魔法", "examples": ["相傳巫師具有治病、驅邪的魔法。"]},
            {"word": "顏料", "examples": ["他用明亮的顏料，將牆壁油漆得煥然一新。"]},
            {"word": "已經", "examples": ["一大清早，許多人都還在睡夢中，他已經端坐在書房中讀了不少書了。"]},
            {"word": "有趣", "examples": ["每天小玲都會將學校有趣的事，一一說給爸媽聽。"]},
            {"word": "混合", "examples": ["他把柳橙、鳳梨、胡蘿蔔、芭樂和蜂蜜、水混合，打成綜合果汁。"]},
            {"word": "橙色", "examples": ["這件橙色的洋裝穿在她身上，顯得十分亮麗。"]},
            {"word": "神奇", "examples": ["化腐朽為神奇。"]},
        ],
    },
    8: {
        "title": "孵蛋的男孩",
        "characters": [
            {"char": "男", "similar_wrong": ["南", "難"], "examples": []},
            {"char": "孩", "similar_wrong": ["還"], "examples": []},
            {"char": "靜", "similar_wrong": ["境", "敬", "竟"], "examples": []},
            {"char": "晨", "similar_wrong": ["沉", "陳", "臣"], "examples": []},
            {"char": "傳", "similar_wrong": ["船"], "examples": []},
            {"char": "雞", "similar_wrong": ["機", "基", "饑", "積", "跡"], "examples": []},
            {"char": "吵", "similar_wrong": ["炒"], "examples": []},
            {"char": "雜", "similar_wrong": ["砸", "扎"], "examples": []},
            {"char": "女", "similar_wrong": ["怒", "努"], "examples": []},
            {"char": "窩", "similar_wrong": ["蝸"], "examples": []},
            {"char": "根", "similar_wrong": ["跟", "更"], "examples": []},
            {"char": "羽", "similar_wrong": ["與", "宇", "雨", "予", "語"], "examples": []},
            {"char": "啄", "similar_wrong": ["卓"], "examples": []},
            {"char": "母", "similar_wrong": ["姆"], "examples": []},
            {"char": "求", "similar_wrong": ["球"], "examples": []},
            {"char": "助", "similar_wrong": ["著", "注", "柱", "祝", "築"], "examples": []},
            {"char": "凡", "similar_wrong": ["繁", "煩"], "examples": []},
            {"char": "孵", "similar_wrong": ["夫"], "examples": []},
            {"char": "離", "similar_wrong": ["黎", "梨"], "examples": []},
        ],
        "compounds": [
            {"word": "平靜", "examples": ["昨天飛機迫降的恐怖經歷，使她的心情一直無法平靜下來。"]},
            {"word": "早晨", "examples": ["春天的早晨，我常被鳥鳴聲喚醒。"]},
            {"word": "吵雜", "examples": ["他住在人聲吵雜的夜市旁，每晚都無法入睡。"]},
            {"word": "女主人", "examples": ["這個家經過女主人的巧手布置，環境舒適，滿室溫馨。"]},
            {"word": "羽毛", "examples": ["孔雀的羽毛色彩豔麗，十分漂亮。"]},
            {"word": "求助", "examples": ["民眾如發現緊急事件，可立即打一一○電話向警方求助。"]},
            {"word": "離開", "examples": ["魚一離開水，很快就會死亡。"]},
            {"word": "凡事", "examples": ["她心思縝密，凡事都能替人設想周到。"]},
        ],
    },
    9: {
        "title": "點亮世界的人",
        "characters": [
            {"char": "歲", "similar_wrong": ["碎", "隧"], "examples": []},
            {"char": "燈", "similar_wrong": ["登"], "examples": []},
            {"char": "賣", "similar_wrong": ["麥", "邁", "脈"], "examples": []},
            {"char": "非", "similar_wrong": ["飛"], "examples": []},
            {"char": "貴", "similar_wrong": ["櫃", "桂"], "examples": []},
            {"char": "買", "similar_wrong": ["脈", "賣", "埋"], "examples": []},
            {"char": "燒", "similar_wrong": ["稍"], "examples": []},
            {"char": "壞", "similar_wrong": ["懷"], "examples": []},
            {"char": "功", "similar_wrong": ["工", "公", "恭", "宮", "供"], "examples": []},
            {"char": "費", "similar_wrong": ["廢"], "examples": []},
            {"char": "絲", "similar_wrong": ["司", "思", "私", "斯"], "examples": []},
            {"char": "敗", "similar_wrong": ["拜"], "examples": []},
            {"char": "實", "similar_wrong": ["拾", "時", "石", "食", "十"], "examples": []},
            {"char": "驗", "similar_wrong": ["厭", "焰"], "examples": []},
            {"char": "呼", "similar_wrong": ["忽", "乎"], "examples": []},
            {"char": "良", "similar_wrong": ["梁", "涼"], "examples": []},
            {"char": "持", "similar_wrong": ["遲", "池"], "examples": []},
            {"char": "宜", "similar_wrong": ["怡", "移", "疑", "儀", "姨"], "examples": []},
        ],
        "compounds": [
            {"word": "油燈", "examples": ["古人常使用油燈來照明。"]},
            {"word": "非常", "examples": ["他是個非常傑出的電視演員。"]},
            {"word": "成功", "examples": ["凡事只要努力不懈，最後一定會成功。"]},
            {"word": "白費", "examples": ["老師教我們的苦心不會白費，我們必更加努力用功以回報之。"]},
            {"word": "燈絲", "examples": ["這顆燈泡的燈絲燒斷了，因此無法發光。"]},
            {"word": "失敗", "examples": ["失敗為成功之母。"]},
            {"word": "實驗", "examples": ["這項藥品的療效目前仍在實驗中。"]},
            {"word": "歡呼", "examples": ["鼓掌歡呼。"]},
            {"word": "改良", "examples": ["洋香瓜經過品種改良後，味道更甜美了。"]},
            {"word": "持久", "examples": ["夫妻間要能互助互諒，婚姻才能持久。"]},
            {"word": "便宜", "examples": ["這件衣服的價錢真便宜。"]},
        ],
    },
    10: {
        "title": "醜小鴨",
        "characters": [
            {"char": "醜", "similar_wrong": ["仇", "愁", "臭"], "examples": []},
            {"char": "鴨", "similar_wrong": ["壓"], "examples": []},
            {"char": "其", "similar_wrong": ["奇", "旗", "騎", "齊"], "examples": []},
            {"char": "特", "similar_wrong": ["德"], "examples": []},
            {"char": "抱", "similar_wrong": ["爆", "暴"], "examples": []},
            {"char": "破", "similar_wrong": ["坡", "婆"], "examples": []},
            {"char": "碗", "similar_wrong": ["晚"], "examples": []},
            {"char": "煩", "similar_wrong": ["繁", "凡"], "examples": []},
            {"char": "雪", "similar_wrong": ["學", "血"], "examples": []},
            {"char": "餓", "similar_wrong": ["惡"], "examples": []},
            {"char": "縮", "similar_wrong": ["索", "所"], "examples": []},
            {"char": "孤", "similar_wrong": ["箍", "估", "姑"], "examples": []},
            {"char": "單", "similar_wrong": ["丹", "擔"], "examples": []},
            {"char": "掉", "similar_wrong": ["調"], "examples": []},
            {"char": "淚", "similar_wrong": ["類"], "examples": []},
            {"char": "鵝", "similar_wrong": ["額", "娥"], "examples": []},
            {"char": "飛", "similar_wrong": ["非"], "examples": []},
            {"char": "迎", "similar_wrong": ["營", "贏", "盈"], "examples": []},
            {"char": "蘆", "similar_wrong": ["爐"], "examples": []},
            {"char": "葦", "similar_wrong": ["尾", "偉", "委"], "examples": []},
        ],
        "compounds": [
            {"word": "醜小鴨", "examples": []},
            {"word": "其中", "examples": []},
            {"word": "特別", "examples": ["這場露天演唱會十分特別，吸引不少的觀眾前往欣賞。"]},
            {"word": "打破", "examples": ["小弟因為打破窗戶玻璃而被父親責罵。"]},
            {"word": "碗盤", "examples": ["用溫水洗碗盤，不會殘留有害物質。"]},
            {"word": "麻煩", "examples": ["這件糾紛處理起來非常麻煩。"]},
            {"word": "雪花", "examples": ["一眼望去，除了雪花滿天飛舞，杳無人跡。"]},
            {"word": "蘆葦", "examples": ["他用蘆葦的莖稈編成一隻蚱蜢。"]},
            {"word": "孤單", "examples": ["由於父母忙於工作，那個小孩常孤單一人在住家附近遊盪。"]},
            {"word": "眼淚", "examples": ["他想到悲傷的往事，難過得直掉眼淚。"]},
            {"word": "天鵝", "examples": ["白色天鵝在湖上悠閒的划水，景致十分恬靜。"]},
            {"word": "迎接", "examples": ["只要我們外出返家，小狗總是搖尾巴迎接我們。"]},
        ],
    },
    11: {
        "title": "蜘蛛救蛋",
        "characters": [
            {"char": "蜘", "similar_wrong": ["枝", "隻", "肢", "脂", "之"], "examples": []},
            {"char": "蛛", "similar_wrong": ["豬", "朱", "珠"], "examples": []},
            {"char": "鴿", "similar_wrong": ["歌", "哥"], "examples": []},
            {"char": "裂", "similar_wrong": ["列", "烈"], "examples": []},
            {"char": "痕", "similar_wrong": ["很", "狠"], "examples": []},
            {"char": "拜", "similar_wrong": ["敗"], "examples": []},
            {"char": "託", "similar_wrong": ["脫", "拖"], "examples": []},
            {"char": "寶", "similar_wrong": ["保", "堡", "飽"], "examples": []},
            {"char": "貝", "similar_wrong": ["背", "備", "倍", "被"], "examples": []},
            {"char": "處", "similar_wrong": ["出", "初", "楚"], "examples": []},
            {"char": "補", "similar_wrong": ["捕"], "examples": []},
            {"char": "內", "similar_wrong": ["耐", "奈"], "examples": []},
            {"char": "石", "similar_wrong": ["拾", "時", "識", "食", "實"], "examples": []},
            {"char": "算", "similar_wrong": ["酸"], "examples": []},
            {"char": "吐", "similar_wrong": ["土"], "examples": []},
            {"char": "顧", "similar_wrong": ["固", "故"], "examples": []},
            {"char": "離", "similar_wrong": ["黎", "梨"], "examples": []},
        ],
        "compounds": [
            {"word": "蜘蛛", "examples": ["某些蜘蛛雖然有毒，但大部分都不會致人於死。", "△蛛蛛、社公　◎◎。"]},
            {"word": "鴿子", "examples": []},
            {"word": "裂痕", "examples": ["這方硯臺已出現裂痕，無法再使用了。"]},
            {"word": "拜託", "examples": ["鄰居出遠門時，常拜託我照顧他們的小狗。"]},
            {"word": "寶貝", "examples": []},
            {"word": "到處", "examples": ["選舉期間到處都貼滿了競選標語。"]},
            {"word": "女媧補天", "examples": []},
            {"word": "內容", "examples": ["本次活動內容有抽獎、親子遊戲等。"]},
            {"word": "石頭", "examples": ["這條健康步道是用許多卵形小石頭鋪成的。"]},
            {"word": "照顧", "examples": ["他非常乖巧懂事，從小就幫忙爸媽照顧弟弟和妹妹。"]},
            {"word": "離開", "examples": ["魚一離開水，很快就會死亡。"]},
        ],
    },
    12: {
        "title": "玉兔搗藥",
        "characters": [
            {"char": "玉", "similar_wrong": ["欲", "獄", "遇", "預", "域"], "examples": []},
            {"char": "兔", "similar_wrong": ["途", "土", "圖"], "examples": []},
            {"char": "搗", "similar_wrong": ["導", "島"], "examples": []},
            {"char": "藥", "similar_wrong": ["要", "鑰"], "examples": []},
            {"char": "姑", "similar_wrong": ["箍", "估", "孤"], "examples": []},
            {"char": "娘", "similar_wrong": ["糧", "涼", "梁"], "examples": []},
            {"char": "養", "similar_wrong": ["仰", "癢"], "examples": []},
            {"char": "仙", "similar_wrong": ["鮮", "先", "掀"], "examples": []},
            {"char": "重", "similar_wrong": ["眾"], "examples": []},
            {"char": "鬧", "similar_wrong": ["腦"], "examples": []},
            {"char": "桂", "similar_wrong": ["櫃", "貴"], "examples": []},
            {"char": "砍", "similar_wrong": ["刊", "看"], "examples": []},
            {"char": "嚇", "similar_wrong": ["下", "夏"], "examples": []},
            {"char": "棍", "similar_wrong": ["滾"], "examples": []},
            {"char": "操", "similar_wrong": ["草"], "examples": []},
            {"char": "夜", "similar_wrong": ["業", "葉", "頁"], "examples": []},
            {"char": "運", "similar_wrong": ["韻"], "examples": []},
        ],
        "compounds": [
            {"word": "玉兔", "examples": ["玉兔東升。"]},
            {"word": "姑娘", "examples": ["嫂嫂閒聊中，偶爾會談到當年她還是個姑娘時的點點滴滴。"]},
            {"word": "仙藥", "examples": []},
            {"word": "桂樹", "examples": []},
            {"word": "嚇一跳", "examples": ["三年不見，他的改變真是令人嚇一跳。"]},
            {"word": "體操", "examples": ["每天早上，爸爸都會在院子裡做體操，以鍛鍊身體。"]},
            {"word": "夜夜", "examples": []},
            {"word": "運動", "examples": ["直線運動、平面運動、等加速運動。"]},
        ],
    },
}

# 年級 -> 資料映射
VOCAB_DATA_MAP = {
    "grade4": VOCAB_DATA_GRADE4,
    "grade2": VOCAB_DATA_GRADE2,
}

# 向後相容 (default to grade4)
VOCAB_DATA = VOCAB_DATA_GRADE4
TOTAL_LESSONS = 12
SEMESTER_NAME = "114學年度第2學期"
GRADE = "四年級"
PUBLISHER = "康軒版"
MIDTERM_RANGE = (1, 6)
FINAL_RANGE = (7, 12)


def get_grade_info(grade_id: str) -> dict:
    """Get grade metadata."""
    return GRADE_REGISTRY.get(grade_id, GRADE_REGISTRY["grade4"])


def get_vocab_data(grade_id: str) -> dict:
    """Get vocabulary data for a specific grade."""
    return VOCAB_DATA_MAP.get(grade_id, VOCAB_DATA_GRADE4)


def get_lessons_in_range(start: int, end: int, grade_id: str = "grade4") -> dict:
    """Get vocabulary data for a range of lessons."""
    data = get_vocab_data(grade_id)
    return {k: v for k, v in data.items() if start <= k <= end}


def get_all_characters_in_range(start: int, end: int, grade_id: str = "grade4") -> list[dict]:
    """Get all characters for a range of lessons, with lesson info."""
    data = get_vocab_data(grade_id)
    chars = []
    for lesson_num, lesson_data in data.items():
        if start <= lesson_num <= end:
            for c in lesson_data["characters"]:
                chars.append({
                    "char": c["char"],
                    "similar_wrong": c["similar_wrong"],
                    "examples": c.get("examples", []),
                    "lesson": lesson_num,
                    "lesson_title": lesson_data["title"],
                })
    return chars


def get_all_compounds_in_range(start: int, end: int, grade_id: str = "grade4") -> list[dict]:
    """Get all compound words for a range of lessons, with lesson info."""
    data = get_vocab_data(grade_id)
    compounds = []
    for lesson_num, lesson_data in data.items():
        if start <= lesson_num <= end:
            for comp in lesson_data.get("compounds", []):
                compounds.append({
                    "word": comp["word"],
                    "examples": comp.get("examples", []),
                    "lesson": lesson_num,
                    "lesson_title": lesson_data["title"],
                })
    return compounds
